#!/bin/sh

NAME="tproxy"
PID="$NAME.pid"
CMD="ruby main.rb"

start()
{
  if [ -e $PID ]; then
    echo "$NAME is running. PID:"`cat ${PID}`
    exit 1
  fi
  echo "$NAME start."
  $CMD
}

stop()
{
  if [ ! -e $PID ]; then
    echo "$NAME stopped."
    exit 1
  fi
  echo "$NAME stop."
  kill `cat ${PID}`
  rm $PID
}

restart()
{
  stop
  sleep 3
  start
}

status()
{
  if [ -e $PID ]; then
    echo "$NAME is running. PID:"`cat ${PID}`
    kill -USR1 `cat ${PID}`
    exit 0
  fi
  echo "$NAME stopped."
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status
    ;;
  *)
    echo "Syntax Error: $NAME [start|stop|restart|status]"
    ;;
esac